// JavaScript array created from the given INSERT statement (order preserved)
export const countries = [
  { id: 1, name: "Afghanista", code: "AF" },
  { id: 2, name: "Albania", code: "AL" },
  { id: 3, name: "Algeria", code: "DZ" },
  { id: 4, name: "Andorra", code: "AD" },
  { id: 5, name: "Angola", code: "AO" },
  { id: 6, name: "Antigua and Barbuda", code: "AG" },
  { id: 7, name: "Argentina", code: "AR" },
  { id: 8, name: "Armenia", code: "AM" },
  { id: 9, name: "Australia", code: "AU" },
  { id: 10, name: "Austria", code: "AT" },
  { id: 11, name: "Azerbaija", code: "AZ" },
  { id: 12, name: "Bahamas", code: "BS" },
  { id: 13, name: "Bahrai", code: "BH" },
  { id: 14, name: "Bangladesh", code: "BD" },
  { id: 15, name: "Barbados", code: "BB" },
  { id: 16, name: "Belarus", code: "BY" },
  { id: 17, name: "Belgium", code: "BE" },
  { id: 18, name: "Belize", code: "BZ" },
  { id: 19, name: "Beni", code: "BJ" },
  { id: 20, name: "Bhuta", code: "BT" },
  { id: 21, name: "Bolivia", code: "BO" },
  { id: 22, name: "Bosnia and Herzegovina", code: "BA" },
  { id: 23, name: "Botswana", code: "BW" },
  { id: 24, name: "Brazil", code: "BR" },
  { id: 25, name: "Brunei", code: "B" },
  { id: 26, name: "Bulgaria", code: "BG" },
  { id: 27, name: "Burkina Faso", code: "BF" },
  { id: 28, name: "Burundi", code: "BI" },
  { id: 29, name: "Cabo Verde", code: "CV" },
  { id: 30, name: "Cambodia", code: "KH" },
  { id: 31, name: "Cameroo", code: "CM" },
  { id: 32, name: "Canada", code: "CA" },
  { id: 33, name: "Central African Republic", code: "CF" },
  { id: 34, name: "Chad", code: "TD" },
  { id: 35, name: "Chile", code: "CL" },
  { id: 36, name: "China", code: "C" },
  { id: 37, name: "Colombia", code: "CO" },
  { id: 38, name: "Comoros", code: "KM" },
  { id: 39, name: "Congo (Brazzaville)", code: "CG" },
  { id: 40, name: "Congo (Kinshasa)", code: "CD" },
  { id: 41, name: "Costa Rica", code: "CR" },
  { id: 42, name: "Côte d'Ivoire", code: "CI" },
  { id: 43, name: "Croatia", code: "HR" },
  { id: 44, name: "Cuba", code: "CU" },
  { id: 45, name: "Cyprus", code: "CY" },
  { id: 46, name: "Czechia", code: "CZ" },
  { id: 47, name: "Denmark", code: "DK" },
  { id: 48, name: "Djibouti", code: "DJ" },
  { id: 49, name: "Dominica", code: "DM" },
  { id: 50, name: "Dominican Republic", code: "DO" },
  { id: 51, name: "Ecuador", code: "EC" },
  { id: 52, name: "Egypt", code: "EG" },
  { id: 53, name: "El Salvador", code: "SV" },
  { id: 54, name: "Equatorial Guinea", code: "GQ" },
  { id: 55, name: "Eritrea", code: "ER" },
  { id: 56, name: "Estonia", code: "EE" },
  { id: 57, name: "Eswatini", code: "SZ" },
  { id: 58, name: "Ethiopia", code: "ET" },
  { id: 59, name: "Fiji", code: "FJ" },
  { id: 60, name: "Finland", code: "FI" },
  { id: 61, name: "France", code: "FR" },
  { id: 62, name: "Gabo", code: "GA" },
  { id: 63, name: "Gambia", code: "GM" },
  { id: 64, name: "Georgia", code: "GE" },
  { id: 65, name: "Germany", code: "DE" },
  { id: 66, name: "Ghana", code: "GH" },
  { id: 67, name: "Greece", code: "GR" },
  { id: 68, name: "Grenada", code: "GD" },
  { id: 69, name: "Guatemala", code: "GT" },
  { id: 70, name: "Guinea", code: "G" },
  { id: 71, name: "Guinea-Bissau", code: "GW" },
  { id: 72, name: "Guyana", code: "GY" },
  { id: 73, name: "Haiti", code: "HT" },
  { id: 74, name: "Honduras", code: "H" },
  { id: 75, name: "Hungary", code: "HU" },
  { id: 76, name: "Iceland", code: "IS" },
  { id: 77, name: "India", code: "IN" },
  { id: 78, name: "Indonesia", code: "ID" },
  { id: 79, name: "Ira", code: "IR" },
  { id: 80, name: "Iraq", code: "IQ" },
  { id: 81, name: "Ireland", code: "IE" },
  { id: 82, name: "Israel", code: "IL" },
  { id: 83, name: "Italy", code: "IT" },
  { id: 84, name: "Jamaica", code: "JM" },
  { id: 85, name: "Japa", code: "JP" },
  { id: 86, name: "Jorda", code: "JO" },
  { id: 87, name: "Kazakhsta", code: "KZ" },
  { id: 88, name: "Kenya", code: "KE" },
  { id: 89, name: "Kiribati", code: "KI" },
  { id: 90, name: "Korea, North", code: "KP" },
  { id: 91, name: "Korea, South", code: "KR" },
  { id: 92, name: "Kuwait", code: "KW" },
  { id: 93, name: "Kyrgyzsta", code: "KG" },
  { id: 94, name: "Laos", code: "LA" },
  { id: 95, name: "Latvia", code: "LV" },
  { id: 96, name: "Lebano", code: "LB" },
  { id: 97, name: "Lesotho", code: "LS" },
  { id: 98, name: "Liberia", code: "LR" },
  { id: 99, name: "Libya", code: "LY" },
  { id: 100, name: "Liechtenstei", code: "LI" },
  { id: 101, name: "Lithuania", code: "LT" },
  { id: 102, name: "Luxembourg", code: "LU" },
  { id: 103, name: "Madagascar", code: "MG" },
  { id: 104, name: "Malawi", code: "MW" },
  { id: 105, name: "Malaysia", code: "MY" },
  { id: 106, name: "Maldives", code: "MV" },
  { id: 107, name: "Mali", code: "ML" },
  { id: 108, name: "Malta", code: "MT" },
  { id: 109, name: "Marshall Islands", code: "MH" },
  { id: 110, name: "Mauritania", code: "MR" },
  { id: 111, name: "Mauritius", code: "MU" },
  { id: 112, name: "Mexico", code: "MX" },
  { id: 113, name: "Micronesia", code: "FM" },
  { id: 114, name: "Moldova", code: "MD" },
  { id: 115, name: "Monaco", code: "MC" },
  { id: 116, name: "Mongolia", code: "M" },
  { id: 117, name: "Montenegro", code: "ME" },
  { id: 118, name: "Morocco", code: "MA" },
  { id: 119, name: "Mozambique", code: "MZ" },
  { id: 120, name: "Myanmar", code: "MM" },
  { id: 121, name: "Namibia", code: "NA" },
  { id: 122, name: "Nauru", code: "NR" },
  { id: 123, name: "Nepal", code: "NP" },
  { id: 124, name: "Netherlands", code: "NL" },
  { id: 125, name: "New Zealand", code: "NZ" },
  { id: 126, name: "Nicaragua", code: "NI" },
  { id: 127, name: "Niger", code: "NE" },
  { id: 128, name: "Nigeria", code: "NG" },
  { id: 129, name: "North Macedonia", code: "MK" },
  { id: 130, name: "Norway", code: "NO" },
  { id: 131, name: "Oman", code: "OM" },
  { id: 132, name: "Pakistan", code: "PK" },
  { id: 133, name: "Palau", code: "PW" },
  { id: 134, name: "Panama", code: "PA" },
  { id: 135, name: "Papua New Guinea", code: "PG" },
  { id: 136, name: "Paraguay", code: "PY" },
  { id: 137, name: "Peru", code: "PE" },
  { id: 138, name: "Philippines", code: "PH" },
  { id: 139, name: "Poland", code: "PL" },
  { id: 140, name: "Portugal", code: "PT" },
  { id: 141, name: "Qatar", code: "QA" },
  { id: 142, name: "Romania", code: "RO" },
  { id: 143, name: "Russia", code: "RU" },
  { id: 144, name: "Rwanda", code: "RW" },
  { id: 145, name: "Saint Kitts and Nevis", code: "K" },
  { id: 146, name: "Saint Lucia", code: "LC" },
  { id: 147, name: "Saint Vincent and the Grenadines", code: "VC" },
  { id: 148, name: "Samoa", code: "WS" },
  { id: 149, name: "San Marino", code: "SM" },
  { id: 150, name: "Sao Tome and Principe", code: "ST" },
  { id: 151, name: "Saudi Arabia", code: "SA" },
  { id: 152, name: "Senegal", code: "SN" },
  { id: 153, name: "Serbia", code: "RS" },
  { id: 154, name: "Seychelles", code: "SC" },
  { id: 155, name: "Sierra Leone", code: "SL" },
  { id: 156, name: "Singapore", code: "SG" },
  { id: 157, name: "Slovakia", code: "SK" },
  { id: 158, name: "Slovenia", code: "SI" },
  { id: 159, name: "Solomon Islands", code: "SB" },
  { id: 160, name: "Somalia", code: "SO" },
  { id: 161, name: "South Africa", code: "ZA" },
  { id: 162, name: "South Suda", code: "SS" },
  { id: 163, name: "Spai", code: "ES" },
  { id: 164, name: "Sri Lanka", code: "LK" },
  { id: 165, name: "Suda", code: "SD" },
  { id: 166, name: "Suriname", code: "SR" },
  { id: 167, name: "Swede", code: "SE" },
  { id: 168, name: "Switzerland", code: "CH" },
  { id: 169, name: "Syria", code: "SY" },
  { id: 170, name: "Tajikista", code: "TJ" },
  { id: 171, name: "Tanzania", code: "TZ" },
  { id: 172, name: "Thailand", code: "TH" },
  { id: 173, name: "Timor-Leste", code: "TL" },
  { id: 174, name: "Togo", code: "TG" },
  { id: 175, name: "Tonga", code: "TO" },
  { id: 176, name: "Trinidad and Tobago", code: "TT" },
  { id: 177, name: "Tunisia", code: "TN" },
  { id: 178, name: "Turkey", code: "TR" },
  { id: 179, name: "Turkmenista", code: "TM" },
  { id: 180, name: "Tuvalu", code: "TV" },
  { id: 181, name: "Uganda", code: "UG" },
  { id: 182, name: "Ukraine", code: "UA" },
  { id: 183, name: "United Arab Emirates", code: "AE" },
  { id: 184, name: "United Kingdom", code: "GB" },
  { id: 185, name: "United States", code: "US" },
  { id: 186, name: "Uruguay", code: "UY" },
  { id: 187, name: "Uzbekista", code: "UZ" },
  { id: 188, name: "Vanuatu", code: "VU" },
  { id: 189, name: "Vatican City", code: "VA" },
  { id: 190, name: "Venezuela", code: "VE" },
  { id: 191, name: "Vietnam", code: "VN" },
  { id: 192, name: "Yeme", code: "YE" },
  { id: 193, name: "Zambia", code: "ZM" },
  { id: 194, name: "Zimbabwe", code: "ZW" }
];